
// <autogenerated />

namespace Public.Analysis.FasbTaxonomies.XmlParsing.DeserializableElementsModels.LabelsElementModels;

// NOTE: Generated code may require at least .NET Framework 4.5 or .NET Core/Standard 2.0.
/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.xbrl.org/2003/linkbase")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.xbrl.org/2003/linkbase", IsNullable = false)]
public partial class linkbase
{

    private linkbaseRoleRef roleRefField;

    private linkbaseLabelLink labelLinkField;

    /// <remarks/>
    public linkbaseRoleRef roleRef
    {
        get
        {
            return this.roleRefField;
        }
        set
        {
            this.roleRefField = value;
        }
    }

    /// <remarks/>
    public linkbaseLabelLink labelLink
    {
        get
        {
            return this.labelLinkField;
        }
        set
        {
            this.labelLinkField = value;
        }
    }
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.xbrl.org/2003/linkbase")]
public partial class linkbaseRoleRef
{

    private string roleURIField;

    private string hrefField;

    private string typeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string roleURI
    {
        get
        {
            return this.roleURIField;
        }
        set
        {
            this.roleURIField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
    public string href
    {
        get
        {
            return this.hrefField;
        }
        set
        {
            this.hrefField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.xbrl.org/2003/linkbase")]
public partial class linkbaseLabelLink
{

    private object[] itemsField;

    private string roleField;

    private string typeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("label", typeof(Label))]
    [System.Xml.Serialization.XmlElementAttribute("labelArc", typeof(Arc))]
    [System.Xml.Serialization.XmlElementAttribute("loc", typeof(Loc))]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
    public string role
    {
        get
        {
            return this.roleField;
        }
        set
        {
            this.roleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

///// <remarks/>
//[System.SerializableAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.xbrl.org/2003/linkbase",TypeName ="loc")]
//public partial class Loc
//{

//    private string hrefField;

//    private string labelField;

//    private string typeField;

//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
//    public string href
//    {
//        get
//        {
//            return this.hrefField;
//        }
//        set
//        {
//            this.hrefField = value;
//        }
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
//    public string label
//    {
//        get
//        {
//            return this.labelField;
//        }
//        set
//        {
//            this.labelField = value;
//        }
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
//    public string type
//    {
//        get
//        {
//            return this.typeField;
//        }
//        set
//        {
//            this.typeField = value;
//        }
//    }
//}

