// <autogenerated />

namespace Public.Analysis.FasbTaxonomies.Parsing.USGaapModels;

using Public.Analysis.FasbTaxonomies.Parsing.Xml;
using System.Xml.Serialization;


/*
 * 2026-09-15 ser/deser models for the fasb us-gaap-2026/stm/*pre-2026.xml
 * mostly autogenerated using visual studio paste special
 */


[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://www.xbrl.org/2003/linkbase")]
[XmlRoot(Namespace = "http://www.xbrl.org/2003/linkbase", IsNullable = false)]
#pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
public partial class linkbase
#pragma warning restore CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
{

    private linkbaseRoleRef roleRefField;

    private linkbasePresentationLink presentationLinkField;

    
    public linkbaseRoleRef roleRef
    {
        get
        {
            return this.roleRefField;
        }
        set
        {
            this.roleRefField = value;
        }
    }

    
    public linkbasePresentationLink presentationLink
    {
        get
        {
            return this.presentationLinkField;
        }
        set
        {
            this.presentationLinkField = value;
        }
    }
}


[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://www.xbrl.org/2003/linkbase")]
public partial class linkbaseRoleRef
{

    private string roleURIField;

    private string hrefField;

    private string typeField;

    
    [XmlAttribute]
    public string roleURI
    {
        get
        {
            return this.roleURIField;
        }
        set
        {
            this.roleURIField = value;
        }
    }

    
    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
    public string href
    {
        get
        {
            return this.hrefField;
        }
        set
        {
            this.hrefField = value;
        }
    }

    
    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}


[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://www.xbrl.org/2003/linkbase")]
public partial class linkbasePresentationLink
{

    private linkbasePresentationLinkLoc[] locField;

    private linkbasePresentationLinkPresentationArc[] presentationArcField;

    private string roleField;

    private string typeField;

    
    [XmlElement("loc")]
    public linkbasePresentationLinkLoc[] loc
    {
        get
        {
            return this.locField;
        }
        set
        {
            this.locField = value;
        }
    }

    
    [XmlElement("presentationArc")]
    public linkbasePresentationLinkPresentationArc[] presentationArc
    {
        get
        {
            return this.presentationArcField;
        }
        set
        {
            this.presentationArcField = value;
        }
    }

    
    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
    public string role
    {
        get
        {
            return this.roleField;
        }
        set
        {
            this.roleField = value;
        }
    }

    
    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}


[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://www.xbrl.org/2003/linkbase")]
public partial class linkbasePresentationLinkLoc
{

    private string hrefField;

    private string labelField;

    private string typeField;

    
    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
    public string href
    {
        get
        {
            return this.hrefField;
        }
        set
        {
            this.hrefField = value;
        }
    }

    
    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
    public string label
    {
        get
        {
            return this.labelField;
        }
        set
        {
            this.labelField = value;
        }
    }

    
    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}


[Serializable]
[XmlType(AnonymousType = true, Namespace = "http://www.xbrl.org/2003/linkbase")]
public partial class linkbasePresentationLinkPresentationArc
{

    private int orderField;

    private string preferredLabelField;

    private string arcroleField;

    private string fromField;

    private string toField;

    private string typeField;

    private string useField;

    
    [XmlAttribute]
    public int order
    {
        get
        {
            return this.orderField;
        }
        set
        {
            this.orderField = value;
        }
    }

    
    [XmlAttribute]
    public string preferredLabel
    {
        get
        {
            return this.preferredLabelField;
        }
        set
        {
            this.preferredLabelField = value;
        }
    }

    
    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
    public string arcrole
    {
        get
        {
            return this.arcroleField;
        }
        set
        {
            this.arcroleField = value;
        }
    }

    
    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
    public string from
    {
        get
        {
            return this.fromField;
        }
        set
        {
            this.fromField = value;
        }
    }

    
    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
    public string to
    {
        get
        {
            return this.toField;
        }
        set
        {
            this.toField = value;
        }
    }

    
    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    
    [XmlAttribute]
    public string use
    {
        get
        {
            return this.useField;
        }
        set
        {
            this.useField = value;
        }
    }
}
